proxies:
- server: 104.192.224.138
  port: 29981
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn: h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 104.192.224.142
  port: 14747
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn: h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 108.181.24.77
  port: 49781
  type: hysteria
  auth_str: ''
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 108.181.24.77
  port: 42529
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn: h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 108.181.5.130
  port: 28065
  type: hysteria2
  password: dongtaiwang.com
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
- server: 176.32.35.90
  port: 443
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 195.154.200.178
  port: 10312
  type: hysteria
  auth_str: ''
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 195.154.200.178
  port: 443
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 195.154.200.40
  port: 2345
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 195.154.200.40
  port: 2345
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn: h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
- server: 195.154.33.70
  port: 28855
  type: hysteria2
  password: dongtaiwang.com
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
- server: 207.174.28.39
  port: 30797
  type: hysteria
  auth_str: dongtaiwang.com
  sni: www.bing.com
  alpn:
  - h3
  udp: true
  skip-cert-verify: true
  up: 11 Mbps
  down: 55 Mbps
